#!/bin/bash

# Get available windows
#swaymsg -t get_tree | jq -r '.nodes[1].nodes[].nodes[] | .. | (.id|tostring) + " " + .name?' | grep -e "[0-9]* ."  )
#swaymsg -t get_tree | jq -r '.nodes | .[] | .nodes | . [] | select(.nodes != null) | .nodes | .[] | select(.name != null) | "\(.id?) \(.name?)"'

#print the workspace number and representation with the json attribut name focus on the workspace based on the id
#
windows=$(swaymsg -t get_workspaces | jq -r '.[] | "\(.name) \(.representation) \(.num)"')

#windows=$(swaymsg -t get_tree | jq -r '.nodes | .[] | .nodes | . [] | select(.nodes != null) | .nodes | .[] | select(.name != null) | "\(.id?) \(.name?)"')

selected=$(echo "$windows" | fzf  --layout=reverse-list --border=rounded --border-label="Fuzzy Windows" | awk '{print $1}')
#echo $selected

##grep swaymsg get tree where workspace is $selected
#tree=$(swaymsg -t get_tree | jq -r '.nodes | .[] | .nodes | . [] | select(. | contains($selected)) |  "\(.name?)"')
#tree=$(swaymsg -t get_tree | jq -r --arg selected "$selected" '.nodes | .[] | .nodes | .[] | select(.name == $selected) | "\(.name)"')
#tree=$(swaymsg -t get_tree | jq -r --arg selected "$selected" '.nodes | .[] | .nodes | .[] | select(.name == $selected) |  .nodes | .[] | select(.name != null) | "\(.id?) \(.name?)"' | awk '{print $1}' | head -n 1) 
tree=$(swaymsg -t get_tree | jq -r --arg selected "$selected" '.nodes | .[] | .nodes | .[] | select(.name == $selected) |  .nodes | .[] | "\(.id?) \(.name?)"' | awk '{print $1}' | head -n 1) 
#echo $tree
# Filter the tree variable based on the selected value
#
#window=$(echo "$tree" | jq -r --arg selected "$selected" '. | select(. | contains($selected))')
#window_id=$(echo "$window" | awk '{print $1}')
#echo $window_id


# Tell sway to focus the window with the extracted ID

#echo $tree


# Tell sway to focus said window
swaymsg -q [con_id="$tree"] focus
