#!/usr/bin/env bash

#volume=$(pactl list sinks | sed -n '10 p' | awk '{print $5}'); 

op=$((pactl list sinks | grep Name | awk '{print $2}' ; ) | cat |  
    fzf  --layout=reverse-list --border=rounded --border-label="Fuzzy Sound" | awk '{print ($1)}')

if [[ -z "$op" ]]; then
    exit 1
fi

pactl set-default-sink $op
