#!/bin/sh

op=$(swaymsg -t get_tree | jq -r '
def windows:    
    ((.nodes // [] | map(windows) | add) +
    (.floating_nodes // [] | map(windows) | add)) // 
(if .name != null then [ {id: .id, name: .name} ] else [] 
end);
  
  .nodes // [] | map(windows) | add | map("\(.id) \(.name)") | .[]
' | fzf --layout=reverse-list --border=rounded --border-label='Fuzzy Switcher')

result=$(echo "$op" | awk '{print $1}')

swaymsg -q [con_id="$result"] focus
