#!/bin/sh

# Use fd to find all .desktop files and extract the Name and Exec fields
fd -e desktop . /usr/share/applications ~/.local/share/applications 2>/dev/null | while read -r desktop_file; do
    name=$(grep -m 1 '^Name=' "$desktop_file" | cut -d '=' -f 2)
    exec=$(grep -m 1 '^Exec=' "$desktop_file" | cut -d '=' -f 2 | sed 's/%.//g')
    
    #no_display=$(grep -m 1 '^NoDisplay=' "$desktop_file" | cut -d '=' -f 2)
    #terminal=$(grep -m 1 '^Terminal=' "$desktop_file" | cut -d '=' -f 2)
    #startupnotify=$(grep -m 1 '^StartupNotify=' "$desktop_file" | cut -d '=' -f 2)


    #if [ -n "$name" ] && [ -n "$exec" ] && [ "$startupnotify" != "false" ] && [ "$no_display" != "true" ] && [ "$terminal" != "true" ] && command -v "$exec" >/dev/null 2>&1; then
    #    echo "$name|$exec"
    #fi

    if [ -n "$name" ] && [ -n "$exec" ]; then
        echo "$name|$exec"
    fi
done | fzf --delimiter="|" --with-nth=1 | cut -d "|" -f 2 | xargs -r swaymsg exec --
