#!/bin/bash
#run swaymsg -rt get_workspaces to see the structure of the json
workspace_num=$(swaymsg -rt get_workspaces | grep -B 47 -A 2 'focused": true' | grep name | cut -d '"' -f 4)
#| grep 'name' | cut -d '"' -f 4)

#get display of the workspace'
width=$(swaymsg -rt get_outputs | grep -A 2 '"current_workspace": "'$workspace_num'"'|grep width|cut -d ':' -f 2|cut -d ',' -f 1)

middlewidth=$(($width/2))


#| grep name | cut -d '"' -f 4)
echo $middlewidth
#return middleewidth so it can be read by sway config

